Woolbright.Web.Corporate/Controllers/ContactController.cs
using System;
using System.Net.Mail;
using System.Net.Mime;
using System.Web.Configuration;
using System.Web.Mvc;
using Woolbright.Web.Corporate.ViewModels;
//using SendGrid;
using Woolbright.Web.Data.DAL;

namespace Woolbright.Web.Corporate.Controllers
{
    public class ContactController : Controller
    {
        private readonly IPropertyRepository _propertyRepository;
    
        public ContactController(
            IPropertyRepository propertyRepository 
        )
        {
            _propertyRepository = propertyRepository;
        }

        // GET: Contact
        public ActionResult Index(string id)
        {
            ViewBag.PropertyId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(SendEmailViewModel emailForm)
        {
            int propertyId = 0;
            try
            {
                var mailMsg = new MailMessage();
                
                // if it's from a property, get the contact. If no contact, use default from web.config
                if (int.TryParse(emailForm.PropertyId, out propertyId))
                {
                    var property = _propertyRepository.GetPropertyById(propertyId);
                    if (property.CorporateContactOverride && property.CorporateContactOverrideValue != null)
                    {
                        // To
                        mailMsg.To.Add(new MailAddress(property.CorporateContactOverrideValue.EmailAddress,
                            property.CorporateContactOverrideValue.FullName));
                        // Bcc default just in case
                        mailMsg.Bcc.Add(new MailAddress(WebConfigurationManager.AppSettings["SendEmailToAddress"],
                            WebConfigurationManager.AppSettings["SendEmailToName"]));
                    }
                    else if (!property.CorporateContactOverride && property.CorporateContact != null)
                    {
                        // To
                        mailMsg.To.Add(new MailAddress(property.CorporateContact.EmailAddress,
                            property.CorporateContact.FullName));
                        // Bcc default just in case
                        mailMsg.Bcc.Add(new MailAddress(WebConfigurationManager.AppSettings["SendEmailToAddress"],
                            WebConfigurationManager.AppSettings["SendEmailToName"]));
                    }
                    else
                    {
                        // To
                        mailMsg.To.Add(new MailAddress(WebConfigurationManager.AppSettings["SendEmailToAddress"],
                            WebConfigurationManager.AppSettings["SendEmailToName"]));
                    }
                }
                else
                {
                    // To
                    mailMsg.To.Add(new MailAddress(WebConfigurationManager.AppSettings["SendEmailToAddress"],
                        WebConfigurationManager.AppSettings["SendEmailToName"]));
                }
               
                // From
                mailMsg.From = new MailAddress(emailForm.Email, emailForm.Name);

                // Subject and multipart/alternative Body
                mailMsg.Subject = "Contact Form: Woolbright Corporate";
                var text = @"Name: " + emailForm.Name + " Message: " + emailForm.Message;
                var html = @"Name: " + emailForm.Name + " Message:<p>" + emailForm.Message + "</p>";
                mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(text, null,
                    MediaTypeNames.Text.Plain));
                mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(html, null,
                    MediaTypeNames.Text.Html));

                // Init SmtpClient and send
                var smtpClient = new SmtpClient("smtp.sendgrid.net", Convert.ToInt32(587));
                var credentials =
                    new System.Net.NetworkCredential(WebConfigurationManager.AppSettings["SendGridAPIId"],
                        WebConfigurationManager.AppSettings["SendGridAPIKey"]);
                smtpClient.Credentials = credentials;
                smtpClient.EnableSsl = true;// NEEDED: wasn't in their documents!!

                smtpClient.Send(mailMsg);

            }
            catch (Exception e)
            {
                Console.WriteLine(e.InnerException);
                ViewBag.PropertyId = propertyId;
                ViewBag.ErrorMessage =
                    "There was an error processing your request. Our Administrator has been informed. Please try again later.";
                // TODO: send an alert somehow that this failed. Fallback plan?
                return View("Index");
            }
            ViewBag.SuccessMessage =
                     "Your request has been sent!";

            return View("EmailSent");
        }

	}
}

Woolbright.Web.Corporate/Controllers/ExecutiveController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Woolbright.Web.Data.DAL;

namespace Woolbright.Web.Corporate.Controllers
{
    public class ExecutiveController : Controller
    {
        private readonly IExecutiveRepository _executiveRepository;
        private readonly IUserProfileRepository _userRepository;
        private readonly IExecutiveSectionRepository _executiveSectionRepository;

        public ExecutiveController(
            IExecutiveRepository executiveRepository, 
            IUserProfileRepository userRepository, 
            IExecutiveSectionRepository executiveSectionRepository)
        {
            _executiveRepository = executiveRepository;
            _userRepository = userRepository;
            _executiveSectionRepository = executiveSectionRepository;
        }

        //[HttpGet]
        public ActionResult ExecutiveProfile(string id)
        {
            // show section in id
            var executiveSectionMappings = _executiveSectionRepository.GetExecutiveSections();

            //var execs = _executiveRepository.GetExecutives()
            //                                .ToList()
            //                                .Where(x => x.ExecutiveSectionMappings.Select(c => string.Equals(c.ExecutiveSection.SectionName, id.Replace("-", " "), StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault())
            //                                .OrderBy(x => x.ExecutiveSectionMappings.Select(c => c.SortOrder).FirstOrDefault());
            //if (!string.IsNullOrEmpty(id))
            //{
            //    ViewBag.Title = id.Replace("-", " ").ToUpper();
            //    var firstOrDefault = _executiveSectionRepository
            //        .GetExecutiveSections()
            //        .FirstOrDefault(x => x.SectionName == id.Replace("-", " "));
            //    if (firstOrDefault != null)
            //        ViewBag.Blurb = firstOrDefault
            //            .SectionBlurb;
            //}
            return View(executiveSectionMappings);
        }
        
        // method to handle sections
        [HttpGet]
        public ActionResult Section(string id)
        {
            // show section in id
            var execs = _executiveRepository.GetExecutives()
                                            .ToList()
                                            .Where(x => x.ExecutiveSectionMappings.Select(c => string.Equals(c.ExecutiveSection.SectionName, id.Replace("-"," "), StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault())
                                            .OrderBy(x => x.ExecutiveSectionMappings.Select(c => c.SortOrder).FirstOrDefault());
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.Title = id.Replace("-", " ").ToUpper();
                var firstOrDefault = _executiveSectionRepository
                    .GetExecutiveSections()
                    .FirstOrDefault(x => x.SectionName == id.Replace("-", " "));
                if (firstOrDefault != null)
                    ViewBag.Blurb = firstOrDefault
                        .SectionBlurb;
            }
            return View(execs);
        }

        // GET: Executive/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var idInt = Convert.ToInt32(id);
            var executive = _executiveRepository.GetExecutiveById(idInt);
            if (executive == null)
            {
                return HttpNotFound();
            }
            // TODO: map excutive to ViewModel


            return View(executive);
        }

        // single method for all executive pages
        //[HttpGet]
        public ActionResult ExecutiveSubMenu()
        {
            // get sections
            var sections = _executiveSectionRepository.GetExecutiveSections()
                .OrderBy(x => x.SortOrder)
                .ToList();
            return PartialView("_ExecutiveSubMenuView", sections);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _executiveRepository.Dispose();
                _userRepository.Dispose();
                _executiveSectionRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Woolbright.Web.Corporate/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Woolbright.Web.Corporate.ViewModels;
using Woolbright.Web.Data.DAL;
using Woolbright.Web.Data.Models;

namespace Woolbright.Web.Corporate.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPropertyRepository _propertyRepository;
        private readonly IResearchArticleRepository _researchArticleRepository;
        public SearchController(
            IPropertyRepository propertyRepository, 
            IResearchArticleRepository researchArticleRepository
            )
        {
            _propertyRepository = propertyRepository;
            _researchArticleRepository = researchArticleRepository;
        }

        // GET: Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string searchString)
        {
            var wrapperModel = new SearchResultsWrapperViewModel();
            if (string.IsNullOrEmpty(searchString)) return View(wrapperModel);
            var stringResults = _propertyRepository
                .GetProperties()
                .Where(
                    // standard fields
                    x => x.Address.IfNullOrWhiteSpace("").Contains(searchString)
                         || x.City.IfNullOrWhiteSpace("").Contains(searchString)
                         || x.WebsiteUrl.IfNullOrWhiteSpace("").Contains(searchString)
                         || x.Zip.IfNullOrWhiteSpace("").Contains(searchString)
                        // overrides possible
                         || (x.DescriptionOverride ? x.DescriptionOverrideValue.Contains(searchString) : x.Description.IfNullOrWhiteSpace("").Contains(searchString))
                         //|| (x.GrossLeasableAreaOverride ? x.GrossLeasableAreaOverrideValue.ToString().Contains(searchString) : x.GrossLeasableArea.ToString().Contains(searchString))
                         //|| (x.MaxContiguousOverride ? x.MaxContiguousOverrideValue.ToString().Contains(searchString) : x.MaxContiguous.ToString().Contains(searchString))
                         //|| (x.MinDivisibleOverride ? x.MinDivisibleOverrideValue.ToString().Contains(searchString) : x.MinDivisible.ToString().Contains(searchString))
                         || (x.NameOverride ? x.NameOverrideValue.Contains(searchString) : x.Name.Contains(searchString))
                         || (x.SquareFootageOverride ? x.SquareFootageOverrideValue.ToString().Contains(searchString) : x.SquareFootage.ToString().Contains(searchString))
                        // tags
                         || (x.TagsOverride ? x.TagsOverrideValue.Any(f => f.TagName.Contains(searchString)) : x.Tags.Any(f => f.TagName.Contains(searchString)))
                        // bayoptions
                         || x.BayOptions.Any(g => g.BaySizeOverride ? g.BaySizeOverrideValue.ToString().Contains(searchString) : g.BaySize.ToString().Contains(searchString))
                         //|| x.BayOptions.Any(g => g.BayTypeOverride ? g.BayTypeOverrideValue.Name.Contains(searchString) : g.BayType.Name.Contains(searchString))
                         || x.BayOptions.Any(g => g.DescriptionOverride ? g.DescriptionOverrideValue.IfNullOrWhiteSpace("").Contains(searchString) : g.Description.IfNullOrWhiteSpace("").Contains(searchString))
                         || x.BayOptions.Any(g => g.ExcerptOverride ? g.ExcerptOverrideValue.IfNullOrWhiteSpace("").Contains(searchString) : g.Excerpt.IfNullOrWhiteSpace("").ToString().Contains(searchString))
                        // Freeform Fields
                         || x.FreeFormFields.Any(g => g.NumberValue.ToString().Contains(searchString))
                         || x.FreeFormFields.Any(g => g.StringValue != null && g.StringValue.ToString().Contains(searchString))
                ).ToList();

            var pdvms = new List<Property>();
            foreach (var item in stringResults)
            {
                var pdvm = new Property
                {
                    Address = item.Address,
                    Address2 = item.Address2,
                    BayOptions = item.BayOptions,
                    City = item.City,
                    FreeFormFields = item.FreeFormFields,
                    PropertyId = item.PropertyId,
                    State = item.State,
                    Tags = item.Tags,
                    WebsiteUrl = item.WebsiteUrl,
                    Zip = item.Zip
                };
                pdvm.Description = item.DescriptionOverride ? pdvm.Description = item.DescriptionOverrideValue : pdvm.Description = item.Description;
                pdvm.GrossLeasableArea = item.GrossLeasableAreaOverride ? item.GrossLeasableAreaOverrideValue : item.GrossLeasableArea;
                pdvm.Location = item.LocationOverride ? item.LocationOverrideValue : item.Location;
                pdvm.MaxContiguous = item.MaxContiguousOverride ? item.MaxContiguousOverrideValue : item.MaxContiguous;
                pdvm.MinDivisible = item.MinDivisibleOverride ? item.MinDivisibleOverrideValue : item.MinDivisible;
                pdvm.Name = item.NameOverride ? item.NameOverrideValue : item.Name;
                pdvm.CorporateContact = item.CorporateContactOverride ? item.CorporateContactOverrideValue : item.CorporateContact;
                pdvm.PropertyContent = item.PropertyContentOverride ? item.PropertyContentOverrideValue : item.PropertyContent;
                pdvm.SquareFootage = item.SquareFootageOverride ? item.SquareFootageOverrideValue : item.SquareFootage;
                pdvms.Add(pdvm);
            }
            wrapperModel.Properties = pdvms;
                
            // research articles
            var racvm = _researchArticleRepository
                .GetResearchArticles()
                .Where(x => x.BodyAzureContainerName.Contains(searchString)
                            || x.Title.Contains(searchString)
                            || x.Tags.Select(m => m.TagName).Contains(searchString))
                .ToList();
            //List
            wrapperModel.ResearchArticles = racvm;

            return View(wrapperModel);
        }
       
    }
}

Woolbright.Web.Corporate/Views/Shared/_ExecutiveSubMenuView.cshtml
@using Woolbright.Web.Data.Models
@model IEnumerable<ExecutiveSection>
@{
    //var parentController = ViewContext.ParentActionViewContext.RouteData.Values["controller"].ToString();
    //var parentAction = ViewContext.ParentActionViewContext.RouteData.Values["action"].ToString();
    var id = string.Empty;
    if (ViewContext.ParentActionViewContext.RouteData.Values["id"] != null) { 
        id = ViewContext.ParentActionViewContext.RouteData.Values["id"].ToString().Replace("-", " ");
    }
}

<div class="navbar-collapse collapse executiveSubMenuDiv">
    <ul class="nav-justified executiveSubMenuUL">
        @foreach (ExecutiveSection es in Model)
        {
            if (id == es.SectionName) 
            { 
                <li class="active"><div class="executiveSubMenuActiveDiv">@Html.ActionLink(es.SectionName, "Section", "Executive", new { id = es.SectionName.Replace(" ", "-") }, null)</div></li>
            }
            else
            {
                <li>@Html.ActionLink(es.SectionName, "Section", "Executive", new { id = es.SectionName.Replace(" ", "-") }, null)</li>
            }
        }
    </ul>
</div>

@*@(ViewContext.ParentActionViewContext.RouteData.Values["controller"].ToString())
<br />
@(ViewContext.ParentActionViewContext.RouteData.Values["action"].ToString())
<br />
@(ViewContext.ParentActionViewContext.RouteData.Values["id"].ToString())*@

Woolbright.Web.Corporate/Views/Shared/_ExecutiveView.cshtml
@model IEnumerable<Woolbright.Web.Data.Models.Executive>

<table class="table table-responsive">
@{
    var counter = 0;
    foreach (var item in Model) {

        if (counter == 0)
        {
            <text><tr><td align="center"></text>
        }
        else
        {
            @:</td><td align="center">
        }
        <table>
            <tr>
                <td>
                    @{
        byte[] photo = item.ProfilePictureContent.ContentBytes;
                string imageSrc = null;
                if (photo != null)
                {
                    MemoryStream ms = new MemoryStream();
                    ms.Write(photo, 0, photo.Length);
                    //ms.Write(photo, 78, photo.Length - 78);
                    string imageBase64 = Convert.ToBase64String(ms.ToArray());
                    imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                }
                }<img src="@imageSrc" alt="Image" width="250" />
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserProfile.FullName, new { @Class = "modal-header" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutiveTitle)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExecutiveBlurb)
            </td>
        </tr>
    </table>
        if (counter == 1)
        {
            counter = -1;
            @:</td></tr>
        }
        counter++;
    }
}  
</table>

Woolbright.Web.Corporate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Woolbright Development, Inc.</title>

    <meta name="description" content="@ViewBag.Description"/>
    <meta name="title" content="@ViewBag.Title"/>
    <meta name="keywords" content="@ViewBag.Keywords"/>

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Content/themes/base/css")*@
    @Scripts.Render("~/bundles/modernizr")

    <!-- Stylesheets Start -->
    <link rel="stylesheet" href="/assets/stylesheets/application.prefix.css">
    <script src="//use.typekit.net/ymh2gal.js"></script>
    <script>
        try {
            Typekit.load();
        } catch (e) {
            //alert("Typekit.load() error");
        }
    </script>
    <!-- Stylesheets End -->

</head>

<body id="site">
<header class="site-header">
    <div class="site-category__container no-mobile">
        <div class="site-category">
            <ul class="site-category__list">
                <li class="active"><a href="/">Corporate</a></li>
                <li><a href="/properties">Properties</a></li>
            </ul><!-- end of .site-category__list -->
        </div><!-- end of .site-category -->
    </div><!-- end of .site-category__container -->
    <div class="site-header__main--container">
        <div class="site-header__main">
            <h1 class="site-title">
                <a href="/">
                    <img class="no-mobile main-logo" src="/assets/svgs/logo-wide-white.svg" alt="@(DateTime.Today.Year) Woolbright Development, Inc." />
                    <img class="no-mobile home-logo" src="/assets/svgs/logo-wide-black.svg" alt="@(DateTime.Today.Year) Woolbright Development, Inc." />
                    <img class="no-desktop" src="/assets/svgs/logo-only.svg" alt="@(DateTime.Today.Year) Woolbright Development, Inc." />
                </a>
            </h1><!-- end of .site-title -->
            <a href="#" class="site-navigation__toggle open-mobile-menu"><img src="/assets/svgs/navicon.svg" alt="Menu"/></a>
            <div class="mobile-search no-desktop">
                <a href="#" id="search-trigger-mobile" class="mobile-search__trigger no-desktop"><i class="fa fa-search"></i></a>
                <div class="search__box mobile">
                    <form action="#" class="search__box--form">
                        <input class="search__box--input" type="text" placeholder="Enter Search Term"/>
                    </form><!-- end of .search__box--form -->
                </div><!-- end of .search__box -->
            </div><!-- end of .mobile-search -->
            <nav class="site-navigation">
                <div class="site-navigation__mobile-elements no-desktop">
                    <div class="site-navigation__mobile-logo">
                        <img src="/assets/svgs/logo-only.svg" alt="@(DateTime.Today.Year) Woolbright Development, Inc."/>
                    </div><!-- end of .site-navigation__mobile-logo -->
                    <div class="site-navigation__mobile-close">
                        <a href="#" class="close-mobile-menu"><img src="/assets/svgs/navicon-close.svg"/></a>
                    </div><!-- end of .site-navigation__mobile-close -->
                    <div class="site-category__container no-desktop">
                        <div class="site-category">
                            <ul class="site-category__list">
                                <li class="active"><a href="/">Corporate</a></li>
                                <li><a href="/properties">Properties</a></li>
                            </ul><!-- end of .site-category__list -->
                        </div><!-- end of .site-category -->
                    </div><!-- end of .site-category__container -->
                </div><!-- end of .site-navigation__mobile-elements -->
                <ul class="site-menu">
                    <li><a href="/"><span data-hover="Home">Home</span></a></li>
                    <li class="has-children">
                        <a href="@(Url.Action("Index", "About"))"><span data-hover="About">About</span></a>
                        <ul class="site-menu__secondary no-desktop">
                            <li><a href="@(Url.Action("CorporateProfile", "About"))">Corporate Profile</a></li>
                            <li><a href="@(Url.Action("ExecutiveProfile", "About"))">Executive Profile</a></li>
                            <li><a href="@(Url.Action("ResearchArticle", "About"))">Research</a></li>
                            <li><a href="@(Url.Action("JobOpportunities", "About"))">Job Opportunities</a></li>
                        </ul><!-- end of .site-menu__secondary -->
                    </li>
                    <li><a href="@(Url.Action("Index", "Portfolio"))"><span data-hover="Portfolio">Portfolio</span></a></li>
                    <li><a href="/contact"><span data-hover="Contact Us">Contact Us</span></a></li>
                    <li class="search">
                        <a href="#" id="search-trigger-desktop"><i class="fa fa-search"></i></a>
                        <div class="search__box desktop">
                            <form action="@(Url.Action("Index", "Search"))" method="POST" class="search__box--form">
                                <input name="searchString" class="search__box--input" type="text" placeholder="Enter Search Term"/>
                                @Html.AntiForgeryToken()
                            </form><!-- end of .search__box--form -->
                        </div><!-- end of .search__box -->
                    </li>
                </ul><!-- end of .site-menu -->
            </nav><!-- end of .site-navigation -->
        </div><!-- end of .site-header__main -->
    </div><!-- end of .site-header__main--container -->
</header><!-- end of .site-header -->
<nav class="site-navigation__secondary">
    <!-- populated dynamically from .site-menu__second-level in .site-navigation -->
</nav><!-- end of .site-navigation__secondary -->
@Scripts.Render("~/bundles/jquery")

@RenderBody()

<div class="site-footer__container">
    <footer class="site-footer">
        <ul class="site-footer__columns">
            <li class="site-footer__column">
                <a href="/" title="Woolbright Development Inc."><img class="site-footer__logo" src="/assets/svgs/logo-only-white.svg" alt="Woolbright Development Inc."/></a>
                <div class="site-footer__address--container">
                    <ul class="site-footer__address">
                        <li class="site-footer__address--label">
                            Corporate Office
                        </li><!-- end of .site-footer__address--label -->
                        <li>2240 NW 19th Street, Suite 801</li>
                        <li>Boca Raton, FL 33431</li>
                        <li>(561) 989–2265</li>
                        <li>
                            <a href="@(Url.Action("Index", "Contact"))">Contact Woolbright Now</a>
                        </li>
                    </ul><!-- end of .site-footer__address -->
                </div><!-- end of .site-footer__address--container -->
            </li><!-- end of .site-footer__column -->
            <li class="site-footer__column">
                <ul class="site-footer__social">
                    <li><a href="#" title="Follow us on LinkedIn"><i class="fa fa-linkedin-square"></i></a></li>
                    <li><a href="#" title="Follow us on Facebook"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="#" title="Follow us on Twitter"><i class="fa fa-twitter"></i></a></li>
                </ul><!-- end of .site-footer__social -->
                <div class="site-footer__copyright">
                    <p>&copy;@(DateTime.Today.Year) Woolbright Development, Inc. <span>–</span> All Rights Reserved
                    </p>
                </div><!-- end of .site-footer__copyright -->
                <div class="site-footer__links">
                    <p><a href="#">Privacy</a> / <a href="#">Disclaimer</a>
                    </p>
                </div><!-- end of .site-footer__links -->
            </li><!-- end of .site-footer__column -->
        </ul><!-- end of .site-footer__columns -->

    </footer><!-- end of .site-footer -->
</div><!-- end of .site-footer__container -->

@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

<!-- JavaScripts Start -->
<script src="/assets/javascripts/application.min.js"></script>
<!-- JavaScripts End -->

</body>
</html>

@* Google Maps *@
@*<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>*@
<script type="text/javascript">
    var geocoder = new google.maps.Geocoder();
    var marker2;
      
    function codeLatLng(name, lat, lng) {
        var latlng = new google.maps.LatLng(lat, lng);
        var infowindow = new google.maps.InfoWindow();
        geocoder.geocode({ 'location': latlng }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                if (results[1]) {
                    map.setZoom(13);
                    marker2 = new google.maps.Marker({
                        position: latlng,
                        map: map,
                        icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',
                        title: 'Test'
                    });
                    map.setCenter(latlng);
                    infowindow.setContent(name);
                    infowindow.open(map, marker2);
                } else {
                    window.alert('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });
    }
    // This is a trick lil functon below...
    // Usage:
    /*
        delay(function () {
            whatever-function();
            }, (delay in seconds));
    */
    var delay = (function () {
        var timer = 0;
        return function (callback, ms) {
            clearTimeout(timer);
            timer = setTimeout(callback, ms);
        };
    })();
</script>  

Woolbright.Web.Corporate/Views/Shared/_SearchView.cshtml
@using (Html.BeginForm("Index", "Search", FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
    <p>
        Search: @Html.TextBox("searchString")<input type="submit" value="Filter" />
    </p>
}
 