Woolbright.Web.CMS/Controllers/ResearchArticleController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Hosting;
using System.Web.Mvc;
using HtmlAgilityPack;
using Woolbright.Web.CMS.ViewModels;
using Woolbright.Web.Data.Classes;
using Woolbright.Web.Data.DAL;
using Woolbright.Web.Data.Models;

namespace Woolbright.Web.CMS.Controllers
{
    public class ResearchArticleController : Controller
    {
        //private CMSContext db = new CMSContext();
        private readonly IResearchArticleRepository _researchArticleRepository;
        private readonly IContentRepository _contentRepository;
        private readonly ITagRepository _tagRepository;
        private readonly IUserProfileRepository _userRepository;
        public ResearchArticleController(
            IResearchArticleRepository researchArticleRepository,
            IContentRepository contentRepository, 
            ITagRepository tagRepository, 
            IUserProfileRepository userRepository
            )
        {
            _researchArticleRepository = researchArticleRepository;
            _contentRepository = contentRepository;
            _tagRepository = tagRepository;
            _userRepository = userRepository;
        }

        // GET: ResearchArticle
        public ActionResult Index()
        {
            // viewmodel
            var viewModel = new ArchiveResearchArticleViewModel
            {
                ArchiveList = GetArchiveList(),
                Articles = _researchArticleRepository.GetResearchArticles()
                    .Where(x => x.DatePublished.Year == DateTime.Today.Year
                                && x.DatePublished.Month == DateTime.Today.Month)
                    .ToList()
            };
            // TODO: if none this month, use last month's?...          
            return View(viewModel);
        }

        public ActionResult Archive(string id)// this is in format 'yyyymm'
        {
            // viewmodel to return
            var viewModel = new ArchiveResearchArticleViewModel();
            // parse date sent
            var postedDateInfo = id.Split('-');
            var month = (int.Parse(postedDateInfo[0]));
            var year = (int.Parse(postedDateInfo[1]));
            // get articles
            viewModel.Articles = _researchArticleRepository.GetResearchArticles()
                //.Include(r => r.Owner)
                .Where(x => x.DatePublished.Month == month && x.DatePublished.Year == year)
                .ToList();          
            // get archives
            viewModel.ArchiveList = GetArchiveList();
         
            return View("Index", viewModel);
        }

        private Dictionary<string, int> GetArchiveList()
        {
            var grouped = (from p in _researchArticleRepository.GetResearchArticles()
                           group p by new { month = p.DatePublished.Month, year = p.DatePublished.Year } into d
                           select new { dt = d.Key.month + "-" + d.Key.year, count = d.Count() }).OrderByDescending(g => g.dt);
            return grouped.ToDictionary(item => item.dt, item => item.count);
        }


        // GET: ResearchArticle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var idInt = Convert.ToInt32(id);
            var researchArticle = _researchArticleRepository.GetResearchArticleById(idInt);
            if (researchArticle == null)
            {
                return HttpNotFound();
            }
            return View(researchArticle);
        }

        // GET: ResearchArticle/Create
        public ActionResult Create()
        {
            var cravm = new CreateResearchArticleViewModel();
            // load available tags for autocomplete
            cravm.Tags = _tagRepository.GetTags()
                .OrderBy(x => x.TagName).ToList();

            FillViewBagBodyFolderChoices();

            return View(cravm);
        }

        private void FillViewBagBodyFolderChoices(string chosenDirectory = null)
        {
            // read available content folders from FTP upload root
            var path =
                HttpContext.Server.MapPath(ConfigurationManager.AppSettings["ResearchArticleFTPUploadRoot"]);
            var subfolders = Directory.GetDirectories(path)
                .OrderBy(x => new DirectoryInfo(x).Name)
                .ToDictionary(v => v, x => new DirectoryInfo(x).Name); // This gets both the full path and the plain directory name
            ViewBag.BodyFolderChoices = !string.IsNullOrEmpty(chosenDirectory)
               ? new SelectList(subfolders, "Value", "Value", chosenDirectory)
               : new SelectList(subfolders, "Value", "Value"); // right now, we only need the directory name to mappath locally per server
        }

        // POST: ResearchArticle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ArticleId,Title,Body,DatePublished,OwnerId")] ResearchArticle researchArticle)
        public ActionResult Create(CreateResearchArticleViewModel researchArticle)
        {
            // catch/check ModelState errs
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            // refill autocomplete regardless if modelstate valid or not
            researchArticle.Tags = _tagRepository.GetTags()
                   .OrderBy(x => x.TagName).ToList();

            // bad model state, return
            if (!ModelState.IsValid) return View(researchArticle);
            
            // make sure that no article exists with this name-date combo
            var dup = _researchArticleRepository.GetResearchArticles()
                .Where(x => x.Title == researchArticle.Title && x.DatePublished == researchArticle.PublishDate);
            if (dup.Any())
            {
                ViewBag.ErrorMessage =
                    "Title/Publish Date combo already in use. Please use a different Title/Publish Date combo.";
                return View(researchArticle);
            }

            var ra = new ResearchArticle
            {
                OwnerId = 1, // TODO: fix this when we go to AD
                Title = researchArticle.Title,
                ShortDescription = researchArticle.ShortDescription,
                DatePublished = researchArticle.PublishDate,
                LastModifiedDate = DateTime.Now
            };
            _researchArticleRepository.InsertResearchArticle(ra);
            _researchArticleRepository.Save(); // to force a new id

            // container name
            ra.BodyAzureContainerName = ConfigurationManager.AppSettings["ResearchArticleBodyAzureContainerNameBase"] +
                                        ra.ArticleId;
            // ---grab the body content files for azure---
            // local path
            ra.BodyRelativeLocalPath = researchArticle.BodyFolderChoices;
            // get filepaths
            var filePaths = GetFilePathsAndUpdateIndexHtml(researchArticle.BodyFolderChoices, ra.BodyAzureContainerName);
            // handle thumbnail - even though 'RequestFilesToContentList' returns a list, we know there's only one image/thumb
            string errorMessage;
            var contentList = ContentSpecific.RequestFilesToContentList(Request.Files, out errorMessage);
            if (!string.IsNullOrEmpty(errorMessage))
            {
                // handle error here.
            }
            // wad up into an Azure obj...
            var lastModifiedDateForIndexHtml = DateTime.Now;
            ra.ThumbnailAzureReference = Azure.PostBlobsToAzure(ra.BodyAzureContainerName, filePaths, contentList[0].ContentBytes, lastModifiedDateForIndexHtml);
           
            // delete everything in the FTP Upload folder after upload. 
            // (since we're modifying the index.html pre-upload it will cause issues later)
            DirectoryInfo downloadedMessageInfo = new DirectoryInfo(HostingEnvironment.MapPath(ConfigurationManager.AppSettings["ResearchArticleBodyRelativeLocalDirectory"] +
                    researchArticle.BodyFolderChoices));

            foreach (FileInfo file in downloadedMessageInfo.GetFiles())
            {
                file.Delete();
            }
            foreach (DirectoryInfo dir in downloadedMessageInfo.GetDirectories())
            {
                dir.Delete(true);
            }
            // maybe leave the directory in case of edit? or remove because it might be confusing later?
            //downloadedMessageInfo.Delete();

            // now the comma delimited tag list
            var tagList = new List<Tag>();
            if (!string.IsNullOrEmpty(researchArticle.TagsOverrideValue))
            {
                var tagArray = researchArticle.TagsOverrideValue.Trim().Split(',');
                tagList.AddRange(from t1 in tagArray
                    where t1.Trim().Length > 0
                    select new Tag
                    {
                        TagId = Guid.NewGuid(), 
                        TagName = t1.Trim(), 
                        CreatedDate = DateTime.Now, 
                        ResearchArticle = ra
                    });
            }
            // if anything entered besides commas and blanks, add it
            if (tagList.Count > 0)
                ra.Tags = tagList;
            
            _researchArticleRepository.UpdateResearchArticle(ra);
            _researchArticleRepository.Save();
            
            FillViewBagBodyFolderChoices();

            return RedirectToAction("Index");

Woolbright.Web.CMS/Views/ResearchArticle/Create.cshtml
@model Woolbright.Web.CMS.ViewModels.CreateResearchArticleViewModel

@{
    ViewBag.Title = "Create Research Article";

    List<string> availableTagList = Model.Tags
        .Select(y => y.TagName)
        .Distinct()
        .ToList();

    if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <p class="alert-danger">@(ViewBag.ErrorMessage)</p>
    }
}

<script>
    // for autocomplete
    var availableTags = @(Html.Raw(Json.Encode(availableTagList)));
</script>

@using (Html.BeginForm("Create", "ResearchArticle", FormMethod.Post, new { enctype = "multipart/form-data", id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()

    <div class="researchArticleEditBody col-md-13 col-md-offset-3">
        <h2>Create Research Article</h2>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Folder", htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.BodyFolderChoices, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownList("BodyFolderChoices", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.BodyFolderChoices, "", new {@class = "text-danger"})*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control researchArticlePublishDate" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Thumbnail (.jpg)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file0" id="file0" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2"><label>Tags</label></div>
            <div class="col-md-10">
                <input type="text" id="TagsOverrideValue" name="TagsOverrideValue" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

    </div>
}
<script>
    $(document).ready(function () {
        $( "#pubDateCalendarIcon" ).on( "click", function() {
            $('#PublishDate').datepicker({ dateFormat: 'mm/dd/yy', changeYear: true });        
        });
        $('#PublishDate').datepicker({ 
            dateFormat: 'mm/dd/yy', 
            changeYear: true,
            showOn: 'both',
            buttonImage: '@(Url.Content("~/Content/Images/calendar.png"))'
        });        
        $("#PublishDate").datepicker( "setDate" , @(DateTime.Today.ToShortDateString()) );
    });
    //var counter = 0;
    //function addFileInput() {
    //    counter++;
    //    $('form input:file').last().after($('<input type="file" name="file' + counter + '" id="file' + counter + '" />'));
    //}
</script>
<script src="~/Scripts/autocomplete.js"></script>

Woolbright.Web.CMS/Views/ResearchArticle/Delete.cshtml
@model Woolbright.Web.Data.Models.ResearchArticle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ResearchArticle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePublished)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Woolbright.Web.CMS/Views/ResearchArticle/Details.cshtml
@model Woolbright.Web.Data.Models.ResearchArticle

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ResearchArticle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BodyFolder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BodyFolder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePublished)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ArticleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Woolbright.Web.CMS/Views/ResearchArticle/Edit.cshtml
@using Woolbright.Web.Data.Classes
@model Woolbright.Web.CMS.ViewModels.EditResearchArticleViewModel
@{
    ViewBag.Title = "Edit";

    // for autocomplete
    List<string> availableTagList = Model.Tags
       .Select(y => y.TagName)
       .Distinct()
       .ToList();
}
<script>
    // for autocomplete
    var availableTags = @(Html.Raw(Json.Encode(availableTagList)));
</script>

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ResearchArticle", FormMethod.Post, new { enctype = "multipart/form-data", id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Research Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ArticleId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BodyFolderChoices, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BodyFolderChoices", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.BodyFolderChoices, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.BodyFolderChoices, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePublished, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DisplayFor(model => model.DatePublished, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DatePublished, "", new {@class = "text-danger"})
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
            @{
                foreach (var content in Model.Thumbnail.OrderBy(x => x.ContentType))
                {
                    switch (content.ContentType)
                    {
                        case Enums.ContentTypes.Image:
                            byte[] contentBytes = content.ContentBytes;
                            string imageSrc = null;
                            if (contentBytes != null)
                            {
                                MemoryStream ms = new MemoryStream();
                                ms.Write(contentBytes, 0, contentBytes.Length);
                                //ms.Write(photo, 78, photo.Length - 78);
                                string imageBase64 = Convert.ToBase64String(ms.ToArray());
                                imageSrc = string.Format("data:image/jpeg;base64,{0}", imageBase64);
                            }
                            <img src="@imageSrc" alt="Image" width="250" />
                            break;
                        case Enums.ContentTypes.Document:
                            @Html.ActionImage(
                                    content.FileName,
                                    "RetrieveFile",
                                    "ResearchArticle",
                                    Url.Content("~/Content/Images/document-universal.png"),
                                    content.FileName,
                                    new { id = content.ContentId })
                            break;
                    }
                    // for deleting...
                    <span class="removeField" style="cursor: pointer; display:inline;" data-contentid="@(content.ContentId)">  X</span>
                }
            }
            </div>
        </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @using System.Text;
                @if (Model.Tags != null)
                {
                    string[] tagList = Model.Tags
                        .Select(x => x.TagName).ToArray();
                    StringBuilder sb = new StringBuilder();
                    for (int x = 0; x < tagList.Count(); x++)
                    {
                        if (x > 0)
                        {
                            sb.Append(", ");
                        }
                        sb.Append(tagList[x]);
                    }
                    <label class="control-label">@sb.ToString()</label>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-md-2"><label>Replace Tags</label></div>
            <div class="col-md-10">                
                <input type="text" id="TagsOverrideValue" name="TagsOverrideValue" />
           </div>
        </div>

                
        <div class="form-group">
            @Html.Label("Existing Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@(Model.ThumbnailAzureReference)" width="200px;"/>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Replace Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<input type="button" value="Add Additional File Upload" name="AddField" onclick="addFileInput();" />
                <br />*@
                <input type="file" name="file0" id="file0" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<div name="inset_form"></div>
<script type="text/javascript">
    @*$('form').on('click', '.removeField', function () {
        // prompt to confirm removal
        var r = confirm("Are you sure you want to remove this content item?");
        // POST to controller
        if (r == true) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            var myForm = '<input type="hidden" name="__RequestVerificationToken" value="' + token + '" />';
            myForm += '<input type="text" name="ResearchArticleId" value="@(Model.ArticleId)" />';
            myForm += '<input type="text" name="ContentId" value="' + $(this).attr("data-contentid") + '" />';// get the ContentID from the 'x' button's data attribute
            $('<form>', {
                "id": "RemoveContentItemForm",
                "html": myForm,
                "action": '@Url.Action("RemoveContentItem", "ResearchArticle")',
                "method": 'post'
            }).appendTo(document.body).submit();
        }
    });*@
    //var counter = 0;
    //function addFileInput() {
    //    counter++;
    //    $('form input:file').last().after($('<input type="file" name="file' + counter + '" id="file' + counter + '" />'));
    //}
</script>
<script src="~/Scripts/autocomplete.js"></script>

Woolbright.Web.CMS/Views/ResearchArticle/Index.cshtml
@using Woolbright.Web.Data.Classes
@model Woolbright.Web.CMS.ViewModels.ArchiveResearchArticleViewModel

@{
    ViewBag.Title = "Research";
}

<div class="container" style="padding-top:60px;">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
   <table class="table">
        <tr>
            <td class="researchArticleArchiveTD">
                <p class="researchArchiveHeader">Archive</p>
                @{
                    foreach (var m in Model.ArchiveList)
                    {
                        DateTime dateConverted = DateTime.Parse(m.Key);
                        var postSingularOrPlural = "Post";
                        if (m.Value > 1)
                        {
                            postSingularOrPlural = "Posts";
                        }
                        <div class="researchArticleArchiveDate">@(dateConverted.ToString("MMMM yyyy"))</div>
                        <br />
                        <div class="researchArticleArchivePostCount">@Html.ActionLink(m.Value + " " + postSingularOrPlural, "Archive", new { id = m.Key }, new { @class = "researchArticleArchivePostCount" })</div>
                    }
                }
            </td>
            <td>
                <h3 class="researchArticleTopHeader">RESEARCH</h3>                                
                @{
                if (Model.Articles.Count < 1)
                {
                    <div>No articles for this period in time.</div>
                }
                }
                @foreach (var item in Model.Articles)
                {
                    var pubDate = item.DatePublished;
                    var pubDateShort = pubDate.ToShortDateString();
                    var pubDateDayOfWeek = pubDate.DayOfWeek.ToString();
                    <div class="researchArticleContainer">
                        <div class="researchArticleTitle">
                            @Html.ActionImage("", "Edit", "ResearchArticle", Url.Content("~/Content/Images/Edit.png"), "Edit", new { id = item.ArticleId })
                            @Html.DisplayFor(modelItem => item.Title)
                        </div>
                        <div class="researchArticleCredits">
                            By @Html.DisplayFor(modelItem => item.Owner.FullName) on @(pubDateDayOfWeek) @(pubDateShort).
                        </div>
                        <div style="display:inline;">
                            <div class="pull-left researchArticleContentLink" data-id="@(item.ArticleId)">
                                <a href="@(Url.Action("Details", new { id = item.ArticleId}))">View Article</a>
                            </div>
                            &nbsp;
                            <p class="researchArticleShortDescription">
                                @Html.DisplayFor(modelItem => item.ShortDescription)
                            </p>
                        </div>
                    </div>
                }
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">
    $(function ($) {
        $('div.researchArticleContentLink').click(function (ev) {
            ev.preventDefault(); // just in case we decide to use anchor tags
            var url = '@Url.Action("GetContentByArticleId", "ResearchArticle")/' + $(this).data('id'); // get id from element clicked
            // setup userfeedback
            $("#UserFeedbackDiv").html('Please wait...<img src="@Url.Content("~/Content/Images/Loading.gif")">');
            $("#UserFeedbackDiv").show();
            // get content
            $('#researchArticleModal .modal-body').html('Content loading...');
            $('#researchArticleModal').modal('show', { backdrop: 'static' });
            $('#researchArticleModal .modal-body').load(url, function (response, status, xhr) {
                if (status == "error") { // handle if error
                    var msg = "Sorry but there was an error: ";
                    $("#UserFeedbackDiv").html(msg + xhr.status + " " + xhr.statusText);
                    // TODO: maybe log error here
                }
                else {
                    $("#UserFeedbackDiv").hide(); // came back ok, hide feeedback
                }
            });
        });
    });
</script>

<div id="researchArticleModal" class="modal fade ">
    <div class="modal-dialog researchArticleModal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Article Content</h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            <div id="UserFeedbackDiv" class="text-center UserFeedbackDiv"></div>
        </div>
    </div>
</div>